version: '3.4'

services:
  python_proxy:
    image: python_proxy
    build:
      context: ./src
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5679 /proxy/proxy.py"]
    ports:
      - 50001:80
      - 5679:5678

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=anoyne@anywhere.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 50011:80

  nginx:
    build:
      context: ./nginx
    ports:
      - 50000:80
    depends_on:
      - postgres
      - python_proxy
